#!/bin/bash

function sleeping() {
    echo "##########################################################"
    echo "# Sleep during ${1}s for $2 service"
    echo "##########################################################"
    sleep 10
}

sudo ./stop_node $1 consul
sudo ./stop_node $1 homeassistant
sudo ./stop_node $1 zigbee2mqtt
sudo ./stop_node $1 grafana
sudo ./stop_node $1 influxdb
sudo ./stop_node $1 emqttd


