#!/bin/bash

TMPDIR="/tmp/docker-home"
SRC="$( (cd $(dirname "$0") && pwd))"

# The script must be running in root
if [ "$(whoami)" != "root" ]; then
	echo "Please run in root"
	exit 0
fi

# Select docker environment
if [ "$2" == "" ]; then
	echo "Usage:"
	echo "$0 environment nodename"
	echo "ex: $0 private/public fullstack"
	exit 0
fi

if [ ! -e "$SRC/$2" ]; then
	echo "$2 node not exist"
	exit 1
fi

# Export nodes variables
set -a
source ./$1.env $1
set +a
export DH_NODE="$2"

# Root remove protection
if [ "$(realpath $DH_DSTDOCKER)" = "/" ]; then
	echo "Cannot store docker images in / folder"
	exit 1
fi

docker-compose -f "${DH_DSTDOCKER}/${DH_NODE}/${DH_ENV}/docker-compose.yml" down
