version: '3'

# export DOCKER_IP=$(docker info | grep -w 'Node Address' | awk '{print $3}')

services:

  consul:
    image:  gliderlabs/consul-server:0.6
    command: "-advertise=${DOCKER_IP} -server -bootstrap"
    container_name: consul
    hostname: ${DOCKER_IP}
    ports:
    - 8500:8500
    environment:
      - SERVICE_8500_CHECK_TCP=true
      - SERVICE_8500_CHECK_INTERVAL=15s
      - SERVICE_8500_CHECK_TIMEOUT=3s

  registrator:
    image: gliderlabs/registrator:v7
    command: "-ip ${DOCKER_IP} consul://${DOCKER_IP}:8500"
    container_name: registrator
    hostname: ${DOCKER_IP}
    depends_on:
    - consul
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock

  influxdb:
    image:  influxdb:1.4.2
    container_name: influxdb
    hostname: ${DOCKER_IP}
    ports:
    - 8086:8086
    environment:
      - INFLUXDB_DB=home_assistant
      - SERVICE_8086_CHECK_TCP=true
      - SERVICE_8086_CHECK_INTERVAL=15s
      - SERVICE_8086_CHECK_TIMEOUT=3s
    volumes:
      - /data/docker/influxdb/data:/var/lib/influxdb

  grafana:
    image:  grafana/grafana:4.6.2
    container_name: grafana
    hostname: ${DOCKER_IP}
    ports:
    - 3000:3000
    environment:
      - SERVICE_3000_CHECK_TCP=true
      - SERVICE_3000_CHECK_INTERVAL=15s
      - SERVICE_3000_CHECK_TIMEOUT=3s
#    volumes:
#      - /data/docker/grafana/dashboards:/data/dashboards
#      - /data/docker/grafana/etc:/etc/grafana
#      - /data/docker/grafana/lib:/var/lib/grafana


    # consul-n1:
    #   image: consul:1.0.1
    #   volumes:
    #     - "./consul/n1:/consul/config"
    #   environment:
    #     - "CONSUL_ALLOW_PRIVILEGED_PORTS="
    #     - "CONSUL_CLIENT_INTERFACE=eth0"
    #     - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true, \"enable_script_checks\": true, \"server\": true}"
    #   command: agent -server -dns-port=53 -bootstrap-expect=1 -ui
    #   ports:
    #     - "8500:8500"
    #     - "8600:8600"
    #
    # homeassistant:
    #     hostname: node-1
    #     image: homeassistant/home-assistant:0.58.1
    #     tty: true
    #     ports:
    #         - 8123:8123
    #     dns:
    #         - 8.8.8.8
    #         - 8.8.4.4
