misc:
  name: Misc
  entities:
    - sun.sun
    - sensor.moon
    - binary_sensor.iss

weather_yr:
  name: yr Weather
  entities:
    - sensor.yr_symbol
    - sensor.yr_temperature
    - sensor.yr_precipitation
    - sensor.yr_humidity

weather_yweather:
  name: yweather Weather
  entities:
    - sensor.yweather_condition
    - sensor.yweather_current
    - sensor.yweather_humidity
    - sensor.yweather_pressure
    - sensor.yweather_temperature
    - sensor.yweather_temperature_max
    - sensor.yweather_temperature_min
    - sensor.yweather_visibility
    - sensor.yweather_wind_speed


weather_camera:
  name: Meteociel Cameras
  entities:
    - camera.mcn
    - camera.mcn1
    - camera.mcn2
    - camera.mcn3
    - camera.mcn4

servers:
  name: Servers
  entities:
    - sensor.consul_passing
    - sensor.consul_criticalwarning


links:
  name: Links
  entities:
    - weblink.google
    - weblink.consul_server
    - weblink.grafana_server
    - weblink.emqttd_server

## VIEWS ##

#default_view:
#  name: Default
#  icon: mdi:home
#  view: yes
#  entities:
#    - group.servers
#    - group.misc
#    - group.links

vweather:
  name: Weather
  view: yes
  entities:
    - group.weather_yr
    - group.weather_yweather
    - group.weather_camera
    - camera.montpellier

vmisc:
  name: Misc
  view: yes
  entities:
    - group.misc
    - group.servers
    - group.links

vcamera:
  name: Camera
  view: yes
  entities:
    - camera.mjpeg_camera
    - camera.mjpeg_camera_2
    - camera.mjpeg_camera_3
    - camera.mjpeg_camera_4
